# Generated by Django 5.2.6 on 2025-10-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='preview_lessons/', verbose_name='Превью'),
        ),
    ]
