# Generated by Django 5.2.6 on 2025-10-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='is_signed',
            field=models.BooleanField(default=True, verbose_name='Подписан'),
        ),
    ]
