# Generated by Django 5.2.6 on 2025-11-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_subscription_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(default=85000, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_payed',
            field=models.BooleanField(default=False, verbose_name='Статус оплаты'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_session',
            field=models.CharField(default=0, max_length=100, verbose_name='Сессия оплаты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
    ]
