# Generated by Django 5.2.6 on 2025-11-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_course_price_payment_is_payed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='is_payed',
            new_name='is_paid',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_session',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Сессия оплаты'),
        ),
    ]
